version: '4.10.0'

services:
  postgres:
    container_name: postgres
    image: postgres:14.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/posgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://postgres:secret@postgres:5432/postgres?sslmode=disable        
    depends_on:
      - postgres
    entrypoint:
      [
        "/ecommers/wait-for.sh",
        "postgres:5432",
        "--",
        "/ecommers/start.sh"
      ]
    command: [ "/ecommers/main" ]
volumes:
  db: